"""Export a run snapshot for the landing page.

The landing hero replays a finished run through the same components the console
uses. That needs a `RunRecord` plus the event stream that produced it.

No recorded call currently carries the demo narrative: every cassette is a
CALL-E test-line role-play that was refused, so all four constraints come back
`unknown`. Rather than fabricate a transcript, this drives the *real* agent -
real planner, real reasoning engine, real scoring, real re-planning - with
scripted call answers, and stamps the output `source: "scripted"` so the UI can
label it honestly.

Swap in a genuine recorded run later and the shape does not change.

    python -m scripts.export_run_snapshot
"""

from __future__ import annotations

import asyncio
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

BACKEND_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BACKEND_ROOT))

from app.agent.placement_agent import PlacementAgent  # noqa: E402
from app.agent.tools.simulated_attendant import ScriptedAttendantActuator  # noqa: E402
from app.data.synthetic_data import FACILITIES, get_patient  # noqa: E402
from app.models.schemas import AgentEvent  # noqa: E402
from app.agent.tools.budget import budget as call_budget  # noqa: E402
from app.services.run_manager import RunRecord, event_message  # noqa: E402

OUT_PATH = (
    BACKEND_ROOT.parent / "frontend" / "src" / "landing" / "data" / "run-snapshot.json"
)


async def main() -> int:
    patient = get_patient("10482")
    # The same actuator a console run in `scripted` mode uses, so every
    # observation is stamped mode=scripted with no call id or duration: nothing
    # in the snapshot can be mistaken for a recorded call. The answers come from
    # app/data/scenarios.py, SNF-002 never appears: the planner prunes it on
    # payer before any dial.
    actuator = ScriptedAttendantActuator()
    called: list[str] = []
    original = actuator.call_facility

    async def recording_call(facility, *args, **kwargs):
        called.append(facility.facility_id)
        return await original(facility, *args, **kwargs)

    actuator.call_facility = recording_call  # type: ignore[method-assign]

    events: list[AgentEvent] = []
    agent = PlacementAgent(actuator, event_sink=events.append)
    run = await agent.run(patient)

    record = RunRecord(
        run_id="snapshot-10482",
        case_id=patient.case_id,
        telephony="scripted",
        run=run,
    )

    snapshot = {
        "source": "scripted",
        "label": "Simulated call answers, real agent logic",
        "disclaimer": (
            "Generated by running the real planner, reasoning engine and "
            "scoring against scripted call answers. No phone call was placed "
            "and no transcript here is a recording."
        ),
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "call_order": called,
        "patient": patient.model_dump(mode="json"),
        # The real directory, so the landing's radius map plots true distances
        # and the contradiction panel quotes the real directory claim.
        "facilities": [f.model_dump(mode="json") for f in FACILITIES],
        # The real ledger, so the landing can show the ceiling without inventing
        # one. The live page prefers /api/budget and falls back to this.
        "budget": {
            "spent": call_budget.spent,
            "ceiling": call_budget.ceiling,
            "remaining": call_budget.remaining,
        },
        "run": record.model_dump(mode="json"),
        "events": [event_message(event) for event in events],
    }

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(json.dumps(snapshot, indent=2) + "\n", encoding="utf-8")

    print(f"wrote {OUT_PATH.relative_to(BACKEND_ROOT.parent)}")
    print(f"  status:      {run.status.value}")
    print(f"  call order:  {' -> '.join(called)}")
    print(f"  events:      {len(events)}")
    print(f"  evaluations: {len(run.evaluations)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
