/**
 * The example run the landing page and /runs/example replay.
 *
 * Generated by `python -m scripts.export_run_snapshot` in backend/, which runs
 * the real planner, reasoning engine and scoring with the backend's scripted
 * attendant: no call is placed, and every observation says `mode: scripted`.
 * `label` and `disclaimer` travel with it so every surface that shows the run
 * can say where it came from. Nothing here is presented as a recorded call.
 */
import type { AgentEvent, BudgetView, Facility, PatientCase, RunRecord } from '@/api/types'
import raw from './run-snapshot.json'

export interface RunSnapshot {
  source: string
  label: string
  disclaimer: string
  generated_at: string
  call_order: string[]
  patient: PatientCase
  facilities: Facility[]
  budget: BudgetView
  run: RunRecord
  events: { type: 'event'; event: AgentEvent }[]
}

export const snapshot = raw as unknown as RunSnapshot

/** Route id the console uses for the example playback. */
export const EXAMPLE_RUN_ID = 'example'

export const snapshotRecord: RunRecord = snapshot.run
export const snapshotRun = snapshot.run.run
export const snapshotEvents: AgentEvent[] = snapshot.events.map((frame) => frame.event)
export const snapshotFacilities = new Map(snapshot.facilities.map((f) => [f.facility_id, f]))
export const snapshotProposal = snapshotRun.proposal
